municipality: bodo

# coordinate system
spatial_reference:
  baerum: "ETRS 1989 UTM Zone 32N"
  kristiansand: "ETRS 1989 UTM Zone 32N"
  oslo: "ETRS 1989 UTM Zone 32N"
  bodo: "ETRS 1989 UTM Zone 33N"